[package]
name = "snomed-ecl"
description = "SNOMED CT Expression Constraint Language (ECL): parser and evaluator for simple expression constraints"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
snomed-core.workspace = true
snomed-store.workspace = true

[dev-dependencies]
snomed-rf2.workspace = true
