[package]
name = "snomed-store"
description = "SNOMED® snapshot store: latest-version resolution, IS-A hierarchy, subsumption. SNOMED®, SNOMED CT®, and IHTSDO® are registered trademarks of International Health Terminology Standards Development Organisation (IHTSDO). Use of the trademarks does not constitute endorsement of this product by IHTSDO. This project is an independent work.."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
snomed-core.workspace = true
snomed-rf2.workspace = true
