[package]
name = "snomed-cli"
description = "SNOMED® command-line interface toolkit for RF2: SCTID validation, release loading, concept lookup, ECL queries, OWL classification and necessary normal form. NOMED®, SNOMED CT®, and IHTSDO® are registered trademarks of International Health Terminology Standards Development Organisation (IHTSDO). Use of the trademarks does not constitute endorsement of this product by IHTSDO. This project is an independent work.."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
authors.workspace = true

[dependencies]
snomed-classify.workspace = true
snomed-core.workspace = true
snomed-ecl.workspace = true
snomed-owl.workspace = true
snomed-rf2.workspace = true
snomed-store.workspace = true
